# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-01-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resource',
            field=models.TextField(blank=True, help_text='allcated resource', null=True, verbose_name='Resources'),
        ),
    ]
